name: Telegram Secret Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Telegram token
        env:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN_NEW }}
        run: |
          if [ -z "$TOKEN" ]; then
            echo "❌ TOKEN IS EMPTY"
            exit 1
          else
            echo "✅ TOKEN EXISTS IN GITHUB"
          fi
